services:
  server:
    build:
      context: ./test-server
      dockerfile: Dockerfile
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      # - "5349:5349/udp"
      # - "5349:5349/tcp"
      # - "49152-65535:49152-65535/udp"
    networks:
      public-net:
        ipv4_address: 10.0.1.10

  client:
    build:
      context: ./trippy-mako
      dockerfile: Dockerfile
    networks:
      client-net:
        ipv4_address: 192.168.1.10
      public-net: # Connect client to the public network as well
        ipv4_address: 10.0.1.11 # Assign a different IP on the public network
    depends_on:
      - server
    stdin_open: true
    tty: true

  peer:
    build:
      context: ./trippy-mako
      dockerfile: Dockerfile
    networks:
      peer-net:
        ipv4_address: 192.168.2.10
      public-net: # Connect client to the public network as well
        ipv4_address: 10.0.1.12 # Assign a different IP on the public network
    depends_on:
      - server
    stdin_open: true
    tty: true

networks:
  public-net:
    ipam:
      config:
        - subnet: 10.0.1.0/24

  client-net:
    ipam:
      config:
        - subnet: 192.168.1.0/24

  peer-net:
    ipam:
      config:
        - subnet: 192.168.2.0/24